--- 
- hosts: localhost #defined in /etc/ansible/hosts
  tasks: #header
    - name: Add 1 user #name of the 1st TASK
      user: #by using that module, we can add users to any Unix system  
          name: bob
          state: present 
      become: yes 
      become_method: sudo #privileges