---
- name:
  hosts: localhost 
  become: yes
  become_method: sudo 
  vars_files: 
            - centos67fedora_values 
            - centos67fedora_values1
            - centos67fedora_values2

  tasks:
      - name: install centos6 
        ec2: 

          key_name: "{{key_name}}"
          instance_type: "{{instance_type}}"
          image: "{{image}}"
          group: "{{group}}"
          count: "{{count}}"
          vpc_subnet_id: "{{vpc_subnet_id}}"
          region: "{{region}}"
          assign_public_ip: yes
          instance_tags: 
                        Name: Centos6

      - name: install centos7
        
        ec2: 
          
          key_name: "{{key_name}}"
          instance_type: "{{instance_type}}"
          image: "{{image}}"
          group: "{{group}}"
          count: "{{count}}"
          vpc_subnet_id: "{{vpc_subnet_id}}"
          region: "{{region}}"
          assign_public_ip: yes
          instance_tags: 
                        Name: Centos7

      - name: install Fedora28 

            
        ec2: 
          
          key_name: "{{key_name}}"
          instance_type: "{{instance_type}}"
          image: "{{image}}"
          group: "{{group}}"
          count: "{{count}}"
          vpc_subnet_id: "{{vpc_subnet_id}}"
          region: "{{region}}"
          assign_public_ip: yes
          instance_tags: 
                        Name: Fedora28  
          

