---
- name: Creates Ubuntu and Debian ec2 
  hosts: localhost
  gather_facts: false
  tasks:
    - name: launch Debian instance
      ec2:
        key_name: myMAC_KEY
        instance_type: t2.micro 
        image: ami-067e80109aff3e2c2
        #wait: yes
        #group:
        count: 1
        vpc_subnet_id: subnet-bc2b54c6
        region: us-east-2b
        assign_public_ip: yes 
        instance_tags: 
                    Name: Debian 
        #monitoring: no 
        #delete_on_termination: true
    
    - name: launch Ubuntu instance 
      ec2:
        key_name: myMAC_KEY
        instance_type: t2.micro 
        image: ami-80a898e5
        #wait: yes
        #group:
        count: 1
        vpc_subnet_id: subnet-bc2b54c6
        region: us-east-2b
        assign_public_ip: yes 
        instance_tags: 
                    Name: Ubuntu  
        #delete_on_termination: true
        user_data: #!/bin/sh 
                   sudo apt-get install python -y     
