---
  - hosts: localhost
    tasks:
        - name: start specific service
          service:
              name: httpd
              state: restarted
          become: yes
          become_methd: sudo 