---
- name: creates ec2 instance 
  hosts: localhost 
  become: yes
  become_method: yes
  vars_file: 
          - vars_values  
  ec2:
      name: "{{name}}"
      key_name: "{{key_name}}"
      vpc_subnet_id: "{{vpc_subnet_id}}"
      instance_type: "{{instance_type}}"
      security_group: "{{security_group}}"
      network:
        assign_public_ip: true
      image_id: "{{image_id}}"
      tags:
        Environment: "{{tag_name}}"