---
- name:
  hosts: localhost 
  become: yes
  become_method: sudo 
  vars_files: 
            - vars_values 

  tasks:
      - name: install centos7 
        ec2: 
          key_name: "{{key_name}}"
          instance_type: "{{instance_type_value}}"
          image: "{{image}}"
          group: "{{group}}"
          count: "{{count}}"
          vpc_subnet_id: "{{vpc_subnet_id}}"
          region: "{{region}}"
          assign_public_ip: yes
          instance_tags: 
                        Name: Centos7