---
- name: This simple playbook creates SSH-KEY
  hosts: target
  become: yes
  become_method: sudo 
  #connection: local
  gather_facts: false
  tasks:
      - name: let's play
        openssh_keypair: 
            path: /tmp/id_ssh_rsa
            size: 2048
        register: res 
      - debug: var=res 

