---
- name: Creates EC2 CentOs Instance by passing values in CLI (not so elegant way of doing it)
  hosts: localhost
  tasks:
    - name: Let's play and have some fun
      ec2:
        key_name: "{{key_name}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet: "{{vpc_subnet}}"
        instance_tags: "{{instance_tags}}"
        group_id: "{{group_id}}"

