--- #sudo pip install boto 
- name: Creates ec2 instance 
  hosts: localhost 
  vars_files:
    - vars_values #regular file (variables : values) 
  tasks:
      - name: Create instance 
        become: true 
        become_method: sudo 
        ec2:
          key_name: "{{key_name}}"
          instance_type: "{{instance_type}}" 
          image: "{{image}}"
          #group: webserver 
          count: "{{count}}"
          vpc_subnet_id: "{{vpc_subnet_id}}" 
          region: "{{region}}"
          #user_data: file.txt
          #user_data: "{{ lookup('file', file.txt') }}"
          user_data: #!/bin/bash
                    yum install r1soft-cdp-enterprise-server -y
                    rsoft-setup --user admin --pass redhat --http-port 80
                    /etc/init.d/cdp-server restart

 
      
      - name: Create a Repository # 
        become: true
        become_method: sudo 
        copy: #from local to remote system
          src: r1soft.repo #copy from here (from that file)
          dest: /etc/yum.repos.d/r1soft.repo #to there 
          
          
      #- name: commands to run r1soft backup system
        
         
      #- name: add 100GB of volume 
      #- ec2_vol:
      #    instance_type: "{{instance_type}}" 
      #    volume_size: 100
      #    register: ec2_vol
          

    
