---
- name: Let's try to install r1soft backup system by using Ansible Playbook
  hostname: localhost

  vars_files: #module name
    - /home/centos/configuration_management_april/p_m_p/prod/vars_values

  tasks:
    - name: Let's play and have some fun
      ec2:
        key_name: "{{key_name}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{count}}"
        vpc_subnet: "{{vpc_subnet}}"
        instance_tags: "{{instance_tags}}"
        group_id: "{{group_id}}"
        region: "{{region}}"


    
