---
- name: Creates ec2 instance 
  hosts: localhost 
  tasks:
      - name: Create instance 
        ec2:
          key_name: myMAC_KEY 
          instance_type: t2.medium 
          image: ami-03cebf94e918675be 
          #group: webserver 
          count: 3 
          vpc_subnet_id: subnet-bc2b54c6 
          region: us-east-2