---
- name: Ansible route 53
  hosts: localhost
  tasks:
    - name: Route53 a record
      route53:
        state: "{{state}}"
        zone: "{{zone}}"
        record: "{{record}}"
        type: A
        ttl: 7200
        value: "{{IP}}" #IP address 
        #wait: yes
